[package]
name = "cat-breeds-k-means"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-machine = "0.5.4"
rand = "0.8.5"
rand_distr = "0.4.3"